dsvs

diff --git a/.github/workflows/analyze-lflist.yml b/.github/workflows/analyze-lflist.yml
--- a/.github/workflows/analyze-lflist.yml
+++ b/.github/workflows/analyze-lflist.yml
@@ -27,7 +27,6 @@ jobs:
     - name: Run Node.js script
       run: node scripts/script.js
 
-    # Verificar si el archivo fue generado
     - name: Verify new_lflist.conf existence
       run: |
         if [ ! -f scripts/new_lflist.conf ]; then
@@ -37,21 +36,24 @@ jobs:
           echo "El archivo new_lflist.conf fue generado correctamente."
         fi
 
-    - name: Upload result as artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: lflist-analysis
-        path: scripts/new_lflist.conf
-
-    # Solo hacer push si el archivo fue generado correctamente
-    - name: Push changes to GitHub
-      if: success()
+    - name: Clone the destination repository
       run: |
-        git config --global user.name "GitHub Action"
-        git config --global user.email "action@github.com"
-        git add scripts/new_lflist.conf
-        git commit -m "Add updated lflist.conf"
-        git push
+        git clone https://github.com/termitaklk/koishi-Iflist.git koishi-Iflist
+        if [ $? -ne 0 ]; then
+            echo "Error: No se pudo clonar el repositorio de destino."
+            exit 1
+        fi
+
+    - name: Move and commit the updated lflist.conf
+      run: |
+        mv scripts/new_lflist.conf koishi-Iflist/
+        cd koishi-Iflist
+        git config user.name "GitHub Action"
+        git config user.email "action@github.com"
+        git add new_lflist.conf
+        git commit -m "Keep only items that match the current year and add missing lists from external .conf files, omitting those with 'KS' in the name"
+        git push origin main  # Push a la rama principal
       env:
-        TOKEN: ${{ secrets.DEST_REPO_TOKEN }}  # Pasar el token secreto al script
+        GITHUB_TOKEN: ${{ secrets.DEST_REPO_TOKEN }}  # Utilizar el token secreto
+
 
